### ISSUE TITLE
Satellite Consumer bug

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#109]
Looks like the satellite consumer was not working on wednesday 18th from about 11:00
<img width="735" alt="Screenshot 2022-05-18 at 15 57 21" src="https://user-images.githubusercontent.com/34686298/169072840-3f618f39-f8bd-43db-910c-12efec3767e0.png">

**Comment by jacobbieker** [comment]
From looking at the logs, this might be because the process is being run when the temporary Zip files still exist. That messes up the check for moving files around, so I think that might fix it.

**Comment by peterdudfield** [comment]
Is there a new version of Satip to deploy?

**Comment by jacobbieker** [comment]
Yeah, 2.6.32, working on that

**Comment by peterdudfield** [comment]
> Yeah, 2.6.32, working on that

let me know if you need any help on deploying it. I think youve been on terraform cloud before right?

**Comment by jacobbieker** [comment]
Yeah, just started the apply

**Comment by jacobbieker** [comment]
Its finished applying, so that should fix the error I was seeing in the logs at least.

**Comment by peterdudfield** [comment]
nice one
<img width="758" alt="Screenshot 2022-05-19 at 09 27 52" src="https://user-images.githubusercontent.com/34686298/169248875-1bc1411f-ff5f-42dc-9e9b-2b61cfb63e29.png">
