### ISSUE TITLE
Sat values between 0 and 1

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#112]
The data pulled by the satellite consumers seems to be between 0 and 1

in [dataloader](https://github.com/openclimatefix/nowcasting_dataloader/blob/main/nowcasting_dataloader/data_sources/satellite/satellite_model.py#L17) the means and stds are very much not 1. 

Have we missed a timings factor somewhere here?

[See batch data here in s3](https://s3.console.aws.amazon.com/s3/buckets/nowcasting-ml-models-development?region=eu-west-1&prefix=batch/satellite/&showversions=false)

or [whole file in s3 ](https://s3.console.aws.amazon.com/s3/object/nowcasting-sat-development?region=eu-west-1&prefix=data/latest/latest.zarr.zip)

**Comment by peterdudfield** [comment]
@jacobbieker would you be able to look into this?

**Comment by jacobbieker** [comment]
Yeah, I can

**Comment by jacobbieker** [comment]
Yeah, the data is scaled to between 0 and 1 here: https://github.com/openclimatefix/Satip/blob/f6583d2fb683b559ff145f4a77f23453b24f3d22/satip/utils.py#L333-L380 to match how the new zarrs are created. Which the v15 dataset I think is earlier than that, so its not in the 0 to 1 range

**Comment by jacobbieker** [comment]
We could I guess calculate new mean and std dev off the RSS zarrs that are on leonardo, and use that? That should end up with similar results?

**Comment by peterdudfield** [comment]
Or we it be better to un-normalize the data coming out of the satellte consumer?

**Comment by jacobbieker** [comment]
It might be better to unnormalize the data from the satellite consumer first, then use the same values as currently being used

**Comment by peterdudfield** [comment]
Just looking at https://s3.console.aws.amazon.com/s3/object/nowcasting-ml-models-development?region=eu-west-1&prefix=batchml/batchml_0.npy, and the values still seem a bit off. 

perhaps we need another look at this

**Comment by jacobbieker** [comment]
Oh, I know what that might be because of, these values aren't converted to integers like we were before. I can add that tomorrow back in so then they should be properly scaled I think.
