### ISSUE TITLE
Benchmark candidate intermediate file formats for EUMETSAT data

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#13]
## Detailed Description
In https://github.com/openclimatefix/nowcasting_dataset/issues/176, it has become clear that opening `.nat` files using SatPy is _way_ too slow to be used by `nowcasting_dataset`.  So we need an intermediate file format, that's easier to load from.

## Possible Implementation

Benchmark & explore several candidate intermediate formats:
  - GeoTIFF
  - NetCDF (one per timestep?)
  - Zarr
  - AVIF (modern compression, lossy or lossless, up to 12 bits per channel. The pillow plug in is only 8bpp) 
  - WebP (modern compression, lossy or lossless, 8 bpp, chroma subsampling) 
  - png
  - lossless JPEG 2000
  - any others

Try imagecodecs and tifffile https://www.lfd.uci.edu/~gohlke/

I like Zarr but it has two downsides for this usage:

- one metadata file describes the entire Zarr dataset. If you mess up that metadata then you pretty much have to throw the whole thing away and start again. In contrast, if you mess up a few GeoTIFF files, just throw the bad ones away
- I don't think Zarr seeks within chunks. It loads entire chunks. Which isn't great for random sampling. In contrast, I think we can seek into NetCDF and geotiff (and maybe others?) 

Related:

- [Benchmarks of Zarr vs TIFF I did back in 2019](https://github.com/JackKelly/storage_benchmarks/tree/master/notebooks), suggesting that Zarr is quite a lot faster.
- [The ipython notebook I wrote in 2019 to convert and reproject `.nat` files to NetCDF](https://github.com/openclimatefix/satellite_image_processing/blob/master/notebooks/convert_native_to_reprojected_netcdf.ipynb)
- [Comparison I made of image file formats downloaded from EUMETSAT](https://github.com/openclimatefix/satellite_image_processing/blob/master/notebooks/compare_EUMETSAT_file_formats.ipynb)
- [The file formats that `pillow` can handle (includes JPEG, PNG, JPEG 2000)](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html)

**Comment by jacobbieker** [comment]
Going to close this, as it seems like Zarr is the winner, and works well for what we have.

**Comment by JackKelly** [comment]
This work is being picked up again in issue #45
