### ISSUE TITLE
Speed up: async

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#144]
## Detailed Description
Should we try using async: here - https://github.com/openclimatefix/Satip/blob/main/satip/eumetsat.py#L424

## Context
- Currently, the data Taylor takes a long time. If we used async it would speed it up
- async might increase the memory usage on production, so we might have to check that

## Possible Implementation
Have a flag to to this loop in async or not, then its easy to turn on and off

**Comment by jacobbieker** [comment]
Yeah, that would probably be good. The async shouldn't use more memory, as the files won't be opened and read till later serially. Data Tailor only allows 3 customizations to run at a time, others get queued up, so it might not speed it up as much as we hope, but would still help.

**Comment by peterdudfield** [comment]
@devsjc would you be interested in this?

**Comment by JasonFengGit** [comment]
I tried to speed up download_tailored_datasets by adding an option to parallel downloads using `concurrent.futures`. Created a draft PR for this: https://github.com/openclimatefix/Satip/pull/250

**Comment by JasonFengGit** [comment]
Could you please review and give some suggestions for the implementation? Thanks!
@jacobbieker @peterdudfield
