### ISSUE TITLE
Improve speed of tests

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/Satip#157]
**Describe the bug**
The `test_download_eumetsat_data` test takes a long time to run, even though the description states that it should only be calling download on a "very short chunk of data".

**To Reproduce**
1. Go to `satip/eumetsat.py`
2. Run `test_download_eumetsat_data`
3. Wait for a long time

**Expected behavior**
The test just downloads a small chunk of data and is relatively fast

**Additional context**
Encountered whilst debugging EUMETSAT API errors breaking forecast in prod

**Comment by JasonFengGit** [comment]
I realized the bottleneck for the download test is the random sleep (0, 600). Hi @jacobbieker, may I know the context of the random sleep? I am wondering if we can reduce the max sleep time or skip the sleep in testing. : )

https://github.com/openclimatefix/Satip/blob/main/satip/download.py#L173

![image](https://github.com/openclimatefix/Satip/assets/40121574/63aaca36-4740-4d76-9718-e297fe47036b)

**Comment by JasonFengGit** [comment]
What’s the amount we should reduce it to? Also, it seems to make more sense if we skip the sleep for the first iteration and sleep a few seconds for the following iterations when the first iter failed.
