### ISSUE TITLE
random order of dataset files

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#182]
## Detailed Description
Could we mix up the order of the dataset. We could make this random
This means if we are running two satellite consumers, then they will pull different files. 
There are other ways to do it, like a queue, but this mixing up of datasets I think is a quick win

## Context
-- it takes quite long (15 mins) sometimes for satellite consumer to run

## Possible Implementation
add shuffle here ish - https://github.com/openclimatefix/Satip/blob/main/satip/app.py#L174

**Comment by peterdudfield** [comment]
what do you reckon to this @jacobbieker

**Comment by jacobbieker** [comment]
Yeah, this sounds good to me. If the satellite data also isn't coming in every 5 minutes, maybe we delay how often we run it? Could also then reduce the amount of duplicate work.

**Comment by jacobbieker** [comment]
I'll open a PR for the randomness, seems sensible to do anyway.
