### ISSUE TITLE
Speed up 15 mins

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#189]
## Detailed Description
I'm worried duplicated customization are being made, and that really slows the process of getting all the 15 mins data. 

Currently at the start of the script we check to see if the files have already been made. 
I wonder before each customization is made, could the app check to see if the file is in s3, if it is, load it, if not run the customization?

## Context
- when the satellite is on backup, it takes about 30 mins to get 1 hour of data. 

## Possible Implementation
See above

**Comment by jacobbieker** [comment]
Yeah, that should be easy enough to change I think

**Comment by peterdudfield** [comment]
Thanks, you ok to have a go at this?
