### ISSUE TITLE
Fix invalid attributes on latest satpy+zarr

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#205]
## Describe the bug
When trying to upgrade to 3.12 in #201 it came up that upgrading to a new version of Zarr and Satpy resulted in the Datasets having non-serializable attributes, related to datetimes. We have the `serialize_attr` function to serialize datetimes, so not sure where that creeps in, but it only happens with newer version of Satpy. 

## Expected behavior
Be able to run `app.py` and the tests without that error occuring.

## Additional context
`freezegun` also seems to have some issues, so it could be related to the datetime functionality used there, although it also occurred when not using `freezegun`.

**Comment by jacobbieker** [comment]
Hi, thanks for reaching out! The first step would be to install satip, then upgrade to the newest version of satpy and zarr. Then try running `app.py`. You will need an [EUMETSAT](https://eoportal.eumetsat.int/cas/login?service=https%3A%2F%2Feoportal.eumetsat.int%2FuserMgmt%2Fcallback%3Fclient_name%3DCasClient) account, although I could also potentially share a raw native file with you if needed. The issue comes up in serialization, so looking into what it happening there could be quite informative.

**Comment by norbline** [comment]
Hello @jacobbieker, can I be assign to this issue?

**Comment by jacobbieker** [comment]
Yep!

**Comment by norbline** [comment]
As far as I understand, the issues you mentioned were related to non-serializable datatime attributes when upgrading to newer versions of Satpy and Zarr. Without further context or specific error messages, it's challenging to pinpoint the exact cause of the problem.

**Comment by jacobbieker** [comment]
Ah, in the process of recreating it, it seems like #228 might actually fix it with the latest versions of Satpy and the like. If it doesn't, then this issue will still be open, but otherwise, that might fix it.
