### ISSUE TITLE
Readme instructions and Development OS / environment used?

### ISSUE THREAD

**Issue by TomPughe** [openclimatefix/Satip#209]
Perhaps more a question than a Feature Proposal, but I'm looking at contributing to the project, but was having some issues running the setup in the README file. I wanted to check what OS, version of python was recommended for developing this project, or any other details of tools/IDE used by existing developers? 

It might be something worth documenting in the README.md file or somewhere else if it isn't already. I could write this up as an updated myself if I get some advice on the best development environment to use.

## Detailed Description
I'm having a few issues with performing the setup instructions in the readme, whilst using Windows, and looking online it seemed like some of the failure could be that the setup is based on using a different OS (perhaps linux based) or I wasn't using the right version of python. For example, when trying to run `conda env create -f environment.yml` I get the following output (concaternated for brevity):

```
$ conda env create -f environment.yml
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
...
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested _libgcc_mutex ==0.1 conda_forge
  - nothing provides requested _openmp_mutex ==4.5 2_gnu
  - nothing provides....
Could not solve for environment specs
The following packages are incompatible
\u251c\u2500 _libgcc_mutex ==0.1 conda_forge does not exist (perhaps a typo or a missing channel);
\u251c\u2500 _openmp_mutex ==4.5 2_gnu does not exist (perhaps a typo or a missing channel);
...
```

## Context
- I think this would make it easier for new users to get started with running and contributing to the project

## Possible Implementation
- Updated README.md to clarify the recommended development setup

**Comment by jacobbieker** [comment]
Hi! Thanks for wanting to contribute, we'd love to make it as easy as possible to do so. 

Currently, all the CI/CD testing, production, and developer machines that we use are Linux-based, so unfortunately, I don't have much experience or access to Windows machines to build the app on. Would it be possible for you to run it in the WSL? I think it should work in that, as that is running Linux. 

The python version should now be Python 3.11, we just updated it this week to that, and regenerated the environment.yml and requirements, so those should work and be up to date for Linux-based systems at least. 

I primarily use PyCharm for development, although I know others on the team use Vim, or VsCode. 

Updating the README would be a great first issue to work on, if you are interested. I can also update it if not though with some more information about setup and the like.

**Comment by TomPughe** [comment]
Thanks! I'll see if I can get it working with a VM or try WSL. I'm happy to take on updating the README if I'm able to get a setup working
