### ISSUE TITLE
Credentials Leaked ? 

### ISSUE THREAD

**Issue by LuisTellezSirocco** [openclimatefix/Satip#214]
## Describe the bug
Hi, I'm not sure if this is a bug or not, but I see some credentials in the modal_processing.py script in the scripts folder. 

I also see some internal directory paths, I don't know if it's a script you want to have public.

## To Reproduce
Just go to the script and look at the header:

```python
os.environ["SAT_API_KEY"] = "SWdEnLvO*****"
os.environ["SAT_API_SECRET"] = "gUQe0ej*****"
```

Maybe you would like check it to renew the tokens or something..

**Comment by jacobbieker** [comment]
Ah shoot, okay, thanks for pointing that out! We'll change them
