### ISSUE TITLE
EUMETSAT cloud mask product

### ISSUE THREAD

**Issue by PaulaPerezL** [openclimatefix/Satip#219]
Apparently Eumesat Cloud Mask product has an hour's delay. How do you work around that delay in your workflow?
 
Thank you very much!

**Comment by peterdudfield** [comment]
We have found that the other images are also a bit delayed, can be an hour. What latency have you found for the other images?

We solve this in the ML side of things. When training the model we only give the model satellite data that is 1 hour before the initialisation time. We've also added a bit of drop out, incase its slightly more or less than 1 hour

Does this make sense?

**Comment by PaulaPerezL** [comment]
High Rate SEVIRI has a latency of 15 minutes and Cloud Mask about one hour.
Your procedure makes complete sense.

Thank you.
