### ISSUE TITLE
India IODC satellite data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#223]
The long range forecast for RUVNL, as well as requiring extended ECMWF data (https://github.com/openclimatefix/nwp-consumer/issues/138) and a new Meteomatics archive, necessitates the collection of Satellite data for India. 

[Part of RUVNL]

**Comment by jacobbieker** [comment]
Processed data is currently being stored here: https://huggingface.co/datasets/openclimatefix/eumetsat-iodc although it will be eventually collated and pushed to the GCP Public Dataset

**Comment by jacobbieker** [comment]
No, its currently filling in random timesteps from the whole archive, 2017-now. Once dagster has its external assets tracker thing, it'll be able to know what's on HF and we can more systematically fill in the dataset. It has some data from all years though.

**Comment by devsjc** [comment]
Currently at 16000/150000.

**Comment by peterdudfield** [comment]
Could speed it up by removing the europe 15 minutes. 
2017 to 2024. Shrink this down to doing 2019 to 2024.

**Comment by devsjc** [comment]
Most of this is now available on huggingface: https://huggingface.co/datasets/openclimatefix/eumetsat-iodc.
