### ISSUE TITLE
Use Pytest for all tests

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#229]
We would like to have all our tests use pytest, rather than some using unittest.

## Context
Most other repos use pytest, so would nice to be consistent.

## Possible Implementation
Replace the unittest framework in the tests with pytest

**Comment by norbline** [comment]
@jacobbieker, Can I be assign to this issue?

**Comment by jacobbieker** [comment]
Yes!

**Comment by vikasgrewal16** [comment]
can i get your insights what is done and what is needed to be done? @norbline

**Comment by jacobbieker** [comment]
@vikasgrewal16 I think @norbline has it going so far, if you want to take #231 that would be great!

**Comment by vikasgrewal16** [comment]
Thanks @jacobbieker I have been working on #231 and will get to you as soon as possible
