### ISSUE TITLE
Add Ability to save to different sinks in app.py

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#230]
Currently, our app.py is hardcoded to save to S3 here: https://github.com/openclimatefix/Satip/blob/b43c9dc38e1024172c3c133781ca21ffc7e2121c/satip/utils.py#L819 

## Detailed Description
It would be great to be able to pass in which backend the app should save to, and use that (i.e. GCP, local, S3, or some other fsspec backend)

## Context
It would be great to have more flexibility in the app

## Possible Implementation
Use fsspec to save to different paths in different backends.

**Comment by vikasgrewal16** [comment]
do you need anything 
Example usage:
# save_to_zarr(my_dataset, 's3://my-bucket/my-data.zarr', backend='s3')
# save_to_zarr(my_dataset, 'file:///path/to/local/data.zarr', backend='file')
# save_to_zarr(my_dataset, 'gcs://my-bucket/my-data.zarr', backend='gcs')

whose working is like this ?

**Comment by jacobbieker** [comment]
Yeah, that would be the ideal kind of interface for this!

**Comment by vikasgrewal16** [comment]
I have made an pr can you please review that pr on this issue @jacobbieker 
and if anything else needed i will be looking forward to you to guide me more on this project
