### ISSUE TITLE
Backfill India IODC satellite imagery to GPD

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/Satip#238]

**Comment by jacobbieker** [comment]
Will run in GCP VM and push to the public dataset. Will wait for kbatch to be turned off before doing so. This takes priority over #237, but can probably be done in parallel.

**Comment by devsjc** [comment]
In progress on VM. Expected to take ~2 weeks.

**Comment by devsjc** [comment]
## 2024-04-29

Conversion is still ongoing.

**Comment by devsjc** [comment]
This is now being done on a monthly basis. The starts of the data are available on the public bucket.

**Comment by jacobbieker** [comment]
Nice! Is this going to be backfilled to the beginning of the IODC imagery? Or only moving forward?
