### ISSUE TITLE
Split integration tests and unit tests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#263]
## Detailed Description
There are both intergations tests and unit tests.
It would be good to split these up, perhaps into different folders. Then we can always run the unit tests.

## Context
- The integration tests need secrets, which I dont think we can give out openly

## Possible Implementation
Split tests into unit and integrations, two different folders.
- update CI to run them seperately

**Comment by Jacqueline-J** [comment]
Hi Peter,

I've taken a look at this. This is the work I've done so far;

1) I split the test in the Satip/tests folder into unit and integration test. Take test_download.py as an example, I split the code into unit_test_download.py and integration_test_download. and stored them in two separate folders, 1) unit_test and 2) integration_test. I did the same for the other 5 tests.

2) I updated the workflows.yaml file from .github/workflows/workflows.yaml. I replaced the  [Run pytest](https://github.com/openclimatefix/Satip/blob/main/.github/workflows/workflows.yaml#L58) command with a pytest tests/unitTest command, and a pytest tests/integrationTest command, ensuring that both tests run separately.

I used the same specifications for both of them as set out in the original Run pytest command. My code is below;
     
'''python
- name: Run unit tests ################
        run: |
          pytest tests/unitTest ################
          export EUMETSAT_USER_KEY="${{ secrets.EUMETSAT_USER_KEY }}"
          export EUMETSAT_USER_SECRET="${{ secrets.EUMETSAT_USER_SECRET }}"
          export PYTEST_COMMAND="pytest $PYTESTCOV $PYTESTXDIST -s --log-level=DEBUG tests/unit" ###
          echo "Will be running this command: $PYTEST_COMMAND"
          eval $PYTEST_COMMAND

      - name: Show coverage
        run: coverage report -m

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

      - name: Run integration tests ################
        run: |
          pytest tests/integrationTest ################
          export EUMETSAT_USER_KEY="${{ secrets.EUMETSAT_USER_KEY }}"
          export EUMETSAT_USER_SECRET="${{ secrets.EUMETSAT_USER_SECRET }}"
          export PYTEST_COMMAND="pytest $PYTESTCOV $PYTESTXDIST -s --log-level=DEBUG tests/integration" ###
          echo "Will be running this command: $PYTEST_COMMAND"
          eval $PYTEST_COMMAND

      - name: Show coverage
        run: coverage report -m

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
'''
That's what I have so far, but I'm not sure of how to test the code to make sure everything is running correctly.

**Comment by peterdudfield** [comment]
Thanks so much for doing this. 

So the unit tests, you should be able to run, but the intergation test will need some secrets. 

Do you want to do a PR, and then we can work out if its right?
