### ISSUE TITLE
Are `y_size_per_chunk` and `x_size_per_chunk` the wrong way round?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#27]
In [`utils.save_dataset_to_zarr`](https://github.com/openclimatefix/Satip/blob/64c67907e80871884b730fd3e49408085abe6ff4/satip/utils.py#L193), the dataarray is first transposed to have the dimensions in the order: `time, x, y, variable`.  Then the chunks are given in the order: timesteps, y, x, channels.  Should y and x be swapped in `chunks`?!  Or have I misunderstood?!

**Comment by jacobbieker** [comment]
Ah, good catch! They should be swapped! Luckily, they are the same for the currently running one, but yeah, they should be swapped

**Comment by JackKelly** [comment]
(BTW, I don't make a habit of randomly reviewing code!  I was discussing with Peter how to convert NWPs to `int16` and was referring to your code to make sure I remembered all the steps!)
