### ISSUE TITLE
Write "proper" datetimes into Zarr

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#29]
## Detailed Description
There's a quirk in xarray's Zarr implementation which means that, out-of-the-box, it corrupts datetimes if appending to the `time` dimension of an existing Zarr.

But there's a simple work-around (described in https://github.com/pydata/xarray/issues/3942#issuecomment-610444090) which means we can write "proper" datetimes into the Zarr (and append):

## Possible Implementation
This is the function I've written for appending NWPs into a Zarr (maybe this function should go into a utils repo?!)

```python
def append_to_zarr(dataset: xr.Dataset, zarr_path: Union[str, Path]):
    zarr_path = Path(zarr_path)
    if zarr_path.exists():
        to_zarr_kwargs = dict(
            append_dim = "time",
        )
    else:
        to_zarr_kwargs = dict(
            # Need to manually set the time units otherwise xarray defaults to using
            # units of *days* (and hence cannot represent sub-day temporal resolution), which corrupts
            # the `time` values when we appending to Zarr.  See:
            # https://github.com/pydata/xarray/issues/5969 and
            # http://xarray.pydata.org/en/stable/user-guide/io.html#time-units
            encoding={
                'time': {
                    'units': 'nanoseconds since 1970-01-01'
                },
            },
        )

    dataset.to_zarr(zarr_path, **to_zarr_kwargs)
```

This definitely isn't urgent... this should probably wait until early 2022 (because it takes a while to re-create the satellite Zarrs!)

**Comment by jacobbieker** [comment]
This might be slightly more urgent, as the nowcasting-dataset expects timestamps in the time dimension. I made a little script that converts the ints back to timestamps and sorts them, as to open a multi-file zarr, the time dimension has to be monotonically increasing, which the easiest way to have this is to just sort the time dimension after we are done appending to it I think. It takes a bit of time to rewrite the zarr with the updated coordinates, but not very long.

```
import pandas as pd

get_time_as_unix = (
    lambda da: [pd.Timestamp(v, unit='s') for v in da.time.values]
)

dataset: xr.Dataset = xr.open_dataset("/run/timeshift/backup/eumetsat_zarr_2020_10_fixed.zarr", engine = 'zarr')
print(dataset)
dataset = dataset.sortby('time')
print(dataset)
dataset["time"] = get_time_as_unix(dataset)
```

**Comment by JackKelly** [comment]
>  the easiest way to have this is to just sort the time dimension after we are done appending to it I think

Ah, so, I could be wrong but I think we have to append to Zarrs in strict order of the `append_dim`.  For example, if you are mostly appending in ascending order, and you append 2021-01-02 before 2021-01-01 then I think bad things happen.  But I could be wrong!  I haven't tested this!  Let me quickly test this now...

**Comment by jacobbieker** [comment]
So Satip doesn't enforce that, and the zarrs at least load fine for me, the time dimension is all jumbled until  I run the above to order it and convert to datetimes. But yeah, maybe if the time dimension is datetimes it has to be in order

**Comment by JackKelly** [comment]
> Satip doesn't enforce that, and the zarrs at least load fine for me, the time dimension is all jumbled

Does slicing work correctly with jumbled times?

**Comment by jacobbieker** [comment]
No it doesn't, that is what was throwing the error, xarray needs the coordinates in order to do the slicing, otherwise it fails

**Comment by jacobbieker** [comment]
That was the impetus behind ordering the time dim actually, so then slicing would work on it

**Comment by JackKelly** [comment]
Got it!

Yeah, I agree that it's probable a good idea to correctly order the time dim!

If it's of interest, here's my quick little experiment (which just confirms what you already know!)

![image](https://user-images.githubusercontent.com/460756/141776288-5c4102c1-0028-4e33-9a63-b30a2e2dc020.png)

**Comment by jacobbieker** [comment]
The cloud masks PR #39 also updates the datetimes to be actual datetimes. I'll add a step to sort the datetimes as well as it goes

**Comment by jacobbieker** [comment]
Zarrs are created with actual datetimes now
