### ISSUE TITLE
rename x --> x_osgb

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#42]
## Detailed Description
Rename x to x_osgb and y to y_osgb

## Context
Good to use the same variable names across different repos
linked with https://github.com/openclimatefix/nowcasting_dataset/pull/558

## Possible Implementation
just rename zarr file, rather than remake all data

**Comment by jacobbieker** [comment]
Yeah, we should be making the full spatial extant zarr soonish, so we'll be remaking the data anyway, and can update it then
