### ISSUE TITLE
Add plots in Geostationary projection to `generate_test_plots.py`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#57]
## Detailed Description
Modify `scripts/generate_test_plots.py` to produce an additional set of plots:  Satellite imagery plotted in geostationary projection with coastlines overlaid, like this:

![image](https://user-images.githubusercontent.com/460756/150364776-a52cd2d2-cba8-4aa6-87f2-be0816a1f120.png)

## Context
The OSGB plot just shows the OSGB domain, which is just over Britain. The Geostationary plot shows the whole geographical extent of the imagery.

It'd be good to have both OSGB and Geostationary plots.

## Possible Implementation
Something like this should work:

```python
ax = plt.axes(projection=ccrs.Geostationary(central_longitude=9.5))
data_array.sel(time="2020-06-01 12:00").plot.pcolormesh(
    ax=ax, 
    transform=ccrs.Geostationary(central_longitude=9.5), 
    x="x", 
    y="y", 
    add_colorbar=False,
)
ax.coastlines();
```

**Comment by peterdudfield** [comment]
from what I remember @JackKelly, you have done this?

**Comment by jacobbieker** [comment]
Yeah, we have that done now with #69
