### ISSUE TITLE
Check that `generate_test_plots.py` still works even when coords have infs / NaNs (e.g. when using the full geo extent of the RSS imagery)

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#58]
## Detailed Description
The code doesn't mask `inf` or `NaN` coordinates.  Need to make sure that `generate_test_plots.py` still works when plotting full geo extent of the RSS imagery

**Comment by jacobbieker** [comment]
It works for geostationary when plotting with those coordinates, not necessarily with OSGB coordinates for the full extant though
