### ISSUE TITLE
Save the channel-specific metadata to the Zarr

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#61]
## Detailed Description
SatPy inserts some useful channel-specific metadata into `data_array.attrs` under the keys `name`, `calibration`, `wavelength`, `standard_name`, and `_satpy_id`.

SatPy stores this channel specific metadata as `attrs` under each `DataArray` in the `Dataset`.  We can't do that because we collapse all the channel-specific `DataArrays` into a single `DataArray` (so we can put multiple channels into a single Zarr chunk). 

## Context
TBH, we don't current use this metadata in our downstream processing. But we might in the future. And other users definitely might want to see this metadata (for when we publish multi-channel SEVIRI data).

## Possible Implementation
So we maybe need to write code to loop through each DataArray's `attrs` and prepend the channel name to the key.  (e.g. the key `name` becomes `VIS006_name` etc.) and then concatenate all the channels' attrs together and then  we can save all those keys and values into the single DataArray's `attrs`?

**Comment by jacobbieker** [comment]
Yeah, that sounds like it would be useful to have, especially the calibration. If even just so we know if we have to calibrate the data tailor cutouts, what to use for those
