### ISSUE TITLE
Rename `stacked_eumetsat_data` to `data`; and rename `variable` to `channels`?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/Satip#66]
## Detailed Description
To be consistent with our other Zarrs (such as NWP and GSP PV Zarrs)

## Possible Implementation
Maybe when we re-compress the existing satellite zarrs using JPEG-XL, we can also rename these?

And then change Satip so it always using `data` and `channels`?

Unless anyone thinks these new names are silly?!  :slightly_smiling_face: 

Related to #62

**Comment by jacobbieker** [comment]
Yeah, sounds good!
