### ISSUE TITLE
Latest data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#71]
## Detailed Description
- Create app.py that saves latest satellite file to a directory. 
- add option of where to save the directory
- add options for the channels to save
- add option for how history of satellite images to get, for example 2 hours. 
- save both satellite and hrv
- good to test that it can save to s3
- save as netcdf file, latest.netcdf and {datetimenow}.netcdf

## Context
Need this for nowcasting 
example of nwp is [here](https://github.com/openclimatefix/MetOfficeDataHub/blob/main/metofficedatahub/app.py)

**Comment by peterdudfield** [comment]
Would be great if this could save the last X hours (say 2 hours) of satellite data. This means the Forecasts (thought nowcasting_dataset) only needs to load one file

**Comment by jacobbieker** [comment]
Yeah, that's the current plan, download the last couple of hours and put the files into a single xarray, which can then be loaded as netCDF files, there will need to be 2 files though, one for HRV and one for non-HRV. Might try the data tailor products, but still need to test if the data values are different
