### ISSUE TITLE
Move constant values

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/Satip#87]
## Detailed Description
Would be great to move constant values (and duplicate) out of the code (functions) to somewhere easy to see. 

- Move list of channels in utils.py
- Move max and min of channels in utils.py

## Context
Keep code tidy

## Possible Implementation
Move to constants file.

**Comment by JasonFengGit** [comment]
Hi @peterdudfield, I am trying to work on this, moving `list of channels` and `max and min` to a new file `constants.py` (correct me if I have misunderstandings). I am wondering how should the naming convention go for the constants? Also, I noticed that there are lists with only one or two numbers like `variable_order=["HRV"], maxs=np.array([103.90016]), mins=np.array([-1.2278595])`. Should these be moved also?

**Comment by JasonFengGit** [comment]
Creating a draft PR for this: https://github.com/openclimatefix/Satip/pull/241

**Comment by JasonFengGit** [comment]
@peterdudfield, could you please advise me on whether I should create new tests for this issue or if running the existing tests is enough, considering the change is relatively trivial in an abstract sense?

**Comment by peterdudfield** [comment]
The current tests are enough I think

**Comment by peterdudfield** [comment]
> Hi @peterdudfield, I am trying to work on this, moving `list of channels` and `max and min` to a new file `constants.py` (correct me if I have misunderstandings). I am wondering how should the naming convention go for the constants? Also, I noticed that there are lists with only one or two numbers like `variable_order=["HRV"], maxs=np.array([103.90016]), mins=np.array([-1.2278595])`. Should these be moved also?

Yea, I think they should. Up to you on naming convention
